module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WISHLIST_COLLECTION:'wishlist',
    CATEGORY_COLLECTION:'category',
    ADDRESS_COLLECTION:'address',
    COUPON_COLLECTION:'coupon',
    WALLET_COLLECTION:'wallet',
}